namespace Rhino.Inside.AutoCAD.Core.Interfaces;

/// <summary>
/// Represents a <see cref="IObjectId.Value"/> reference that is used to track
/// and identify any <see cref="IEntity"/> generated by an AWI application.
/// Such <see cref="IEntity"/>s are referred to as 'AWI application owned'.
/// </summary>
/// <remarks>
/// <see cref="IObjectIdTag"/>s are used to keep a reference to any AutoCAD object
/// instance created by an AWI application, typically so they can be re-collected
/// for resource purposes, or deleted if the user re-runs the AWI application. For
/// example, if the users runs the RCP solver (the <see cref="IPanelSolver"/>)
/// and creates a new layout, any <see cref="IPanel"/>s created are
/// <see cref="IObjectIdTag"/>ged so they can be identified and deleted if the user
/// runs the solver again. This mechanism forms the primary function of the instance
/// management infrastructure.
/// </remarks>
public interface IObjectIdTag
{
    /// <summary>
    /// The name of the Group Number Value Types Reference (DXF).
    /// <see href="https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-3F0380A5-1C15-464D-BC66-2C5F094BCFB9">
    /// See a table of all the available DXF codes here.
    /// </see>
    /// </summary>
    GroupCodeValue GroupCode { get; }

    /// <summary>
    /// Corresponds to a <see cref="IObjectId.Value"/>. This value is used to obtain the
    /// <see cref="IEntity"/> from the AutoCAD database if it is valid and exists.
    /// </summary>
    long Id { get; }
}